/**
 * The worker boundary.
 *
 * Imported by both sides, so the message shapes cannot drift apart. Every
 * message carries the `id` of the request that caused it: the search is fast
 * enough that a query usually completes before the next keystroke, but when it
 * does not, the client discards anything whose id is stale rather than trying
 * to interrupt work already in flight.
 */

export type Tier = 'common' | 'standard' | 'full' | 'extended';

/** Narrowest first, which is the order the picker shows them in. */
export const TIERS: readonly Tier[] = ['common', 'standard', 'full', 'extended'];

/** Treated by the engine as "no limit on how many words a result may use". */
export const UNLIMITED_WORDS = 64;

/**
 * The term classes of decision D63, in the plan's table order, which is the
 * order the engine's `classCounts` reports them in and the bit each holds in
 * `crates/anagram-core/src/classes.rs`. A term of an anagram is a word of the
 * dictionary or a term of one of these; `words` is the absence of a class.
 * Numerals and leet are generated by the engine from the pool and the
 * readings table; the rest come from the class files through `dict:build`.
 */
export const CLASSES = ['numerals', 'symbols', 'shorthand', 'blends', 'acronyms', 'leet', 'names', 'slang'] as const;
export type ClassName = (typeof CLASSES)[number];
export const WORDS = 'words';

export function isClassName(value: string): value is ClassName {
  return (CLASSES as readonly string[]).includes(value);
}

/**
 * The characters Search turns leet on for by default (roadmap N5): the three
 * symbols whose letter is plain. A digit in a text is usually a number, so
 * digits are off. The reader changes it a character at a time under the field.
 */
export const SEARCH_LEET_DEFAULT: readonly string[] = ['$', '!', '@'];

/**
 * The term classes Search admits before the reader turns any on: none, which
 * is D63's "words alone is the default everywhere". Every class is one tick of
 * the Terms control, and the address carries the ones turned on. D63's table
 * reads numerals and symbols as on for Search, which its own prose and the
 * manual contradict; this constant is where that call lives.
 */
export const SEARCH_CLASSES_DEFAULT: readonly ClassName[] = [];

export type Query = {
  readonly input: string;
  readonly tier: Tier;
  /**
   * The term classes admitted beside the tier's words: a class is on by
   * choice, and words alone (empty) is the default everywhere.
   */
  readonly classes: readonly ClassName[];
  /**
   * The characters of the input the search also tries as their leet letters
   * (`$` as s, `7` as t or v), one search per reading, merged and tagged; at
   * most three take effect. Empty is none.
   */
  readonly leet: readonly string[];
  /** Words shorter than this are removed from the vocabulary. */
  readonly minWordLen: number;
  readonly maxWords: number;
  readonly mustInclude: readonly string[];
  /**
   * Words taken out of the dictionary for this query: a class whose every
   * spelling is excluded is gone, and one with other spellings shows those.
   */
  readonly mustExclude: readonly string[];
  /**
   * How the input's digits and symbols are read, where the reader chose
   * other than the default (`self`): item → reading name, a letter or `drop`
   * (`readings.ts`). Empty for the defaults, which is nearly always.
   */
  readonly reading: Readonly<Record<string, string>>;
};

export const DEFAULT_QUERY: Omit<Query, 'input'> = {
  tier: 'standard',
  classes: [],
  leet: [],
  // 2 keeps the good short words (`of`, `to`, `an`) while excluding lone
  // letters, which are the single largest source of noise in results.
  minWordLen: 2,
  maxWords: UNLIMITED_WORDS,
  mustInclude: [],
  mustExclude: [],
  reading: {},
};

/**
 * What a row carries beside its words when any of them is not a plain word of
 * the dictionary under the text as typed: each such word's class, how every
 * word is written (a leet character where its letter went: `hake$`), and the
 * leet reading the row was found under. `classes` and `written` are parallel
 * to the row.
 */
export type RowTag = {
  /** Per word: its class, or null for a word of the dictionary. */
  readonly classes: readonly (ClassName | null)[];
  /** Per word: as shown, the record's word with the leet character written in. */
  readonly written: readonly string[];
  /** The leet reading: character → letter. Empty under the text as typed. */
  readonly reading: Readonly<Record<string, string>>;
};

export type DictCounts = {
  readonly common: number;
  readonly standard: number;
  /** English OpenList at the pinned revision, plus the listed forms' letters-words. */
  readonly full: number;
  /** The pinned list plus the site's own additions: every word that ships. */
  readonly extended: number;
  readonly signatures: number;
  /** The listed forms the dictionary carries; absent from an artifact built before them. */
  readonly forms?: number;
  /** How many of the forms are words the pinned list lacks, which every tier gains. */
  readonly formOnly?: number;
  /** How many terms each class carries; absent from a manifest built before the classes. */
  readonly classes?: Readonly<Partial<Record<ClassName, number>>>;
};

/**
 * One listed form, as the dictionary carries it beside the letters-word: the
 * page shows `don't` for `dont` and lists `it's` beside `its`. Results, keys
 * and ids carry the letters alone.
 */
export type DictForm = {
  readonly letters: string;
  readonly form: string;
  /** Rows show the form: it is the only spelling of its letters. */
  readonly shown: boolean;
};

export type ManifestFile = {
  readonly name: string;
  /** Size decoded. The check that a compressed transfer arrived intact. */
  readonly bytes: number;
  /** Size of the sibling `.br`, when the build produced one. */
  readonly brotliBytes?: number;
  readonly sha256: string;
};

export type Manifest = {
  readonly schemaVersion: number;
  readonly builtAt: string;
  readonly source: { readonly repo: string; readonly rev: string };
  readonly counts: DictCounts;
  readonly files: Readonly<Record<string, ManifestFile>>;
};

export type SolveStats = {
  readonly candidates: number;
  readonly elapsedMs: number;
};

// ------------------------------------------------------------------ requests

export type Request =
  | { readonly k: 'init'; readonly id: number; readonly baseUrl: string }
  | {
      readonly k: 'solve';
      readonly id: number;
      readonly query: Query;
      readonly first: number;
      /**
       * Search-effort ceiling in DFS nodes. Exists so a pathological input
       * cannot hang the worker, and so the truncation path can be exercised
       * by a test rather than taken on faith.
       */
      readonly maxNodes?: number;
    }
  | { readonly k: 'page'; readonly id: number; readonly offset: number; readonly len: number }
  | {
      /**
       * The total for a query, and nothing else: no results, and the session
       * the list pages through is left as it was. Answered with `count`. The
       * search page asks it for a filter's words while the reader types.
       */
      readonly k: 'count';
      readonly id: number;
      readonly query: Query;
      readonly maxNodes?: number;
    }
  | {
      /**
       * Materialize up to `limit` results in one go, for export. Separate from
       * `page` because it is not part of the browsing session: it must not move
       * the paging cursor or be mistaken for the visible list.
       */
      readonly k: 'collect';
      readonly id: number;
      readonly limit: number;
    }
  | { readonly k: 'random'; readonly id: number; readonly index: string }
  | { readonly k: 'spellings'; readonly id: number; readonly word: string; readonly tier: Tier }
  | {
      /** Whether `word` is a word of `tier`, or a term of one of `classes` (none when absent). */
      readonly k: 'lookup';
      readonly id: number;
      readonly word: string;
      readonly tier: Tier;
      readonly classes?: readonly ClassName[];
    }
  | { readonly k: 'masks'; readonly id: number; readonly words: readonly string[] }
  | {
      /**
       * Each word's frequency byte, as the dictionary carries it. The Build
       * page reads it to say how common a word is.
       */
      readonly k: 'zipf';
      readonly id: number;
      readonly words: readonly string[];
    };

// ----------------------------------------------------------------- responses

/** Fatal codes render the unsupported-browser screen; the rest are recoverable. */
export type ErrorCode =
  | 'WASM_INIT'
  | 'FETCH_FAILED'
  | 'BAD_ARTIFACT'
  | 'UNKNOWN_WORD'
  | 'NOT_A_SUBSET'
  /** One character occurs more than 127 times; the engine's counts are bytes. */
  | 'TOO_MANY_REPEATS'
  /** More than six different digits and symbols; the pool has six slots for them. */
  | 'TOO_MANY_CHARACTERS'
  /** The digits would make more numerals than the engine generates. */
  | 'TOO_MANY_NUMERALS'
  | 'INTERNAL';

export const FATAL_ERRORS: readonly ErrorCode[] = ['WASM_INIT', 'BAD_ARTIFACT'];

export type Response =
  | {
      readonly k: 'ready';
      readonly id: number;
      readonly counts: DictCounts;
      readonly builtAt: string;
      readonly loadMs: number;
      /** The listed forms, read from the artifact once; empty for one built without them. */
      readonly forms: readonly DictForm[];
      /** How many terms the dictionary carries in each class; all zero for words alone. */
      readonly classes: Readonly<Record<ClassName, number>>;
    }
  | {
      readonly k: 'count';
      readonly id: number;
      /**
       * Decimal string, not a number: totals routinely exceed
       * `Number.MAX_SAFE_INTEGER`. A leading `>` marks a floor rather than an
       * exact figure (the true total overflowed 128 bits).
       */
      readonly total: string;
      readonly candidates: number;
      /**
       * The text's own row is not among the results, so `total` is one fewer
       * than its letters alone would give. The text itself, its words in any
       * order, is never a result. When other words share a word's letters the
       * row is shown with one of those and nothing is left out; when none do,
       * the row goes, and the page says so beside the count.
       */
      readonly textLeftOut: boolean;
      /**
       * The digits and symbols of the text that no term of this query uses,
       * in the order they first appear: the count is zero for the lack of
       * them, and the page says so. Empty for a text of letters, and once a
       * class or a leet reading covers them.
       */
      readonly unused: string;
      /** The characters leet was tried on: at most three of those asked for. */
      readonly leet: readonly string[];
    }
  | {
      readonly k: 'batch';
      readonly id: number;
      readonly offset: number;
      readonly rows: readonly (readonly string[])[];
      /** No further results exist after this batch. */
      readonly done: boolean;
      /**
       * The search stopped at its node budget rather than running out of
       * answers. A short batch means very different things in the two cases,
       * and the interface has to be able to tell them apart.
       */
      readonly truncated: boolean;
      /**
       * Per row, its tag, or null for a row of words alone under the text as
       * typed; absent when no row of the batch has one, which is every batch
       * of a search with no class on and no leet.
       */
      readonly tags?: readonly (RowTag | null)[];
    }
  | { readonly k: 'solved'; readonly id: number; readonly stats: SolveStats }
  | { readonly k: 'spellings'; readonly id: number; readonly words: readonly string[] }
  | {
      readonly k: 'lookup';
      readonly id: number;
      readonly found: boolean;
      /**
       * The class that carries the word when no tier of the dictionary does:
       * the first of the asked classes in table order, as a row's tag names
       * it. Absent for a word of the tier, and for a word nothing has.
       */
      readonly termClass?: ClassName;
    }
  | { readonly k: 'masks'; readonly id: number; readonly masks: readonly number[] }
  | { readonly k: 'zipf'; readonly id: number; readonly zipf: readonly number[] }
  | {
      readonly k: 'collected';
      readonly id: number;
      readonly rows: readonly (readonly string[])[];
      /** Every result was written; nothing was cut off by the limit or a budget. */
      readonly complete: boolean;
      /** As on `batch`. */
      readonly tags?: readonly (RowTag | null)[];
    }
  | {
      readonly k: 'error';
      readonly id: number;
      readonly code: ErrorCode;
      readonly message: string;
    };

/** `1234567` -> `1,234,567`; passes through a `>` prefix. */
export function formatCount(total: string): string {
  const floor = total.startsWith('>');
  const digits = floor ? total.slice(1) : total;
  const grouped = digits.replace(/\B(?=(\d{3})+(?!\d))/g, ',');
  return floor ? `more than ${grouped}` : grouped;
}
