// The readings table. GENERATED by `scripts/gen-readings.py` from `scripts/readings.json`; do not edit.
//
// Read by `readings.ts`, whose tests walk `READING_CASES` and check this
// file against the JSON; the Rust side carries the identical table in
// `crates/anagram-core/src/readings_table.rs`.

/** One symbol the item finder knows. */
export type SymbolSpec = {
  /** An item only with a letter on both sides; elsewhere it is punctuation. */
  readonly insideWordOnly: boolean;
};

export const SYMBOLS: Readonly<Record<string, SymbolSpec>> = {
  '@': { insideWordOnly: false },
  '$': { insideWordOnly: true },
  '!': { insideWordOnly: true },
  '?': { insideWordOnly: true },
  '&': { insideWordOnly: false },
  '%': { insideWordOnly: false },
  '+': { insideWordOnly: false },
  '#': { insideWordOnly: false },
};

/** The defaults, as a queue's summary records them. */
export const READING_DEFAULTS: Readonly<Record<string, string>> = {
  'numbers': 'drop',
  'ordinals': 'drop',
  'symbols': 'drop',
};

/** `[input, overrides as item:name pairs, the read text]`, walked by the tests. */
export const READING_CASES: readonly (readonly [string, string, string])[] = [
  ['Blink-182', '', 'Blink-'],
  ['Blink-182', '182:drop', 'Blink-'],
  ['2 Fast 2 Furious', '', ' Fast  Furious'],
  ['2 Fast 2 Furious', '2:drop', ' Fast  Furious'],
  ['Area 51', '', 'Area '],
  ['Reacher season 4', '', 'Reacher season '],
  ['Reacher season 4', '4:drop', 'Reacher season '],
  ['Sardar 2', '2:drop', 'Sardar '],
  ['Como 1907', '', 'Como '],
  ['2026–27 UEFA Champions League', '', '– UEFA Champions League'],
  ['9/11 conspiracy theories', '', '/ conspiracy theories'],
  ['Charles Spencer, 9th Earl Spencer', '', 'Charles Spencer,  Earl Spencer'],
  ['18th BRICS summit', '', ' BRICS summit'],
  ['1st 2nd 3rd 4th 11th 12th 13th 21st 100th', '', '        '],
  ['1000th 10,000th 100,000th 0th', '', '   '],
  ['1th 2st 5thavenue', '', 'th st thavenue'],
  ['Ke$ha', '', 'Keha'],
  ['P!nk', '', 'Pnk'],
  ['wh?t', '', 'wht'],
  ['Hello!', '', 'Hello!'],
  ['what?', '', 'what?'],
  ['$5 off', '', '$ off'],
  ['Bl1nk', '', 'Blnk'],
  ['h3llo l33t', '', 'hllo lt'],
  ['Se7en', '', 'Seen'],
  ['R2D2 C3PO MI6 3M mp3', '', 'RD CPO MI M mp'],
  ['1337', '', ''],
  ['AT&T', '', 'ATT'],
  ['Me@Home', '', 'MeHome'],
  ['@home', '', 'home'],
  ['C++', '', 'C'],
  ['#1 fan', '', ' fan'],
  ['50% off', '', ' off'],
  ['1,000', '', ''],
  ['1,000,000', '', ''],
  ['90210', '', ''],
  ['Beverly Hills 90210', '', 'Beverly Hills '],
  ['1,2', '', ','],
  ['007', '', ''],
  ['Route 66!', '', 'Route !'],
  ['Ben Shelton 🎾 2026', '', 'Ben Shelton 🎾 '],
  ['Beyoncé 2', '', 'Beyoncé '],
  ['Test 3 and 3', '5:drop', 'Test  and '],
  ['Test 3 and 3', '3:spell', 'Test  and '],
  ['', '', ''],
  ['no items here', '', 'no items here'],
];
