// The readings table. GENERATED by `scripts/gen-readings.py` from `scripts/readings.json`; do not edit.
//
// Read by `readings.ts`, whose tests walk `READING_CASES` and check this
// file against the JSON; the Rust side carries the identical table in
// `crates/anagram-core/src/readings_table.rs`.

/** One symbol the reading step knows. */
export type SymbolSpec = {
  /** The keyboard letter it stands for, if any. */
  readonly letter?: string;
  /** The word it is spelled as, if any. */
  readonly spell?: string;
  readonly default: 'letter' | 'spell';
  /** An item only with a letter on both sides; elsewhere it is punctuation. */
  readonly insideWordOnly: boolean;
};

/** Each digit's names, the cardinal first and its homophones after. */
export const DIGIT_NAMES: readonly (readonly string[])[] = [
  ['zero', 'oh'],
  ['one', 'won'],
  ['two', 'to', 'too'],
  ['three'],
  ['four', 'for'],
  ['five'],
  ['six'],
  ['seven'],
  ['eight', 'ate'],
  ['nine'],
];

/** The keyboard letter each digit stands for inside a word, or null. */
export const DIGIT_LETTERS: readonly (string | null)[] = [
  'o', 'i', null, 'e', 'a', 's', null, 't', null, null,
];

export const TEENS: readonly string[] = ['ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen'];
export const TENS: readonly string[] = ['twenty', 'thirty', 'forty', 'fifty', 'sixty', 'seventy', 'eighty', 'ninety'];
export const HUNDRED = 'hundred';
export const THOUSAND = 'thousand';

/** Ordinals that are not the cardinal plus `th`. */
export const ORDINAL_IRREGULAR: Readonly<Record<string, string>> = {
  one: 'first',
  two: 'second',
  three: 'third',
  five: 'fifth',
  eight: 'eighth',
  nine: 'ninth',
  twelve: 'twelfth',
};

export const SYMBOLS: Readonly<Record<string, SymbolSpec>> = {
  '@': { letter: 'a', spell: 'at', default: 'letter', insideWordOnly: false },
  '$': { letter: 's', default: 'letter', insideWordOnly: true },
  '!': { letter: 'i', default: 'letter', insideWordOnly: true },
  '&': { spell: 'and', default: 'spell', insideWordOnly: false },
  '+': { spell: 'plus', default: 'spell', insideWordOnly: false },
};

/** A number with more digits than this is dropped unless read digit by digit. */
export const MAX_SPELLED_DIGITS = 4;

/** The defaults, as a queue's summary records them. */
export const READING_DEFAULTS: Readonly<Record<string, string>> = {
  'numbers': 'spell',
  'long_numbers': 'drop',
  'ordinals': 'spell',
  'inside_a_word': 'letter',
  '@': 'letter',
  '$': 'letter',
  '!': 'letter',
  '&': 'spell',
  '+': 'spell',
};

/** `[input, overrides as item:name pairs, the read text]`, walked by the tests. */
export const READING_CASES: readonly (readonly [string, string, string])[] = [
  ['Blink-182', '', 'Blink- one hundred eighty two'],
  ['Blink-182', '182:digits', 'Blink- one eight two'],
  ['Blink-182', '182:drop', 'Blink-'],
  ['Blink-182', '182:year', 'Blink- one hundred eighty two'],
  ['2 Fast 2 Furious', '', 'two Fast two Furious'],
  ['2 Fast 2 Furious', '2:too', 'too Fast too Furious'],
  ['2 Fast 2 Furious', '2:to', 'to Fast to Furious'],
  ['2 Fast 2 Furious', '2:letter', 'two Fast two Furious'],
  ['Area 51', '', 'Area fifty one'],
  ['Area 51', '51:digits', 'Area five one'],
  ['Reacher season 4', '', 'Reacher season four'],
  ['Reacher season 4', '4:drop', 'Reacher season '],
  ['Reacher season 4', '4:for', 'Reacher season for'],
  ['Sardar 2', '2:drop', 'Sardar '],
  ['Como 1907', '', 'Como one thousand nine hundred seven'],
  ['Como 1907', '1907:year', 'Como nineteen oh seven'],
  ['european election 2014', '2014:year', 'european election twenty fourteen'],
  ['India at the 2026 Asian Games', '', 'India at the two thousand twenty six Asian Games'],
  ['India at the 2026 Asian Games', '2026:year', 'India at the twenty twenty six Asian Games'],
  ['2026–27 UEFA Champions League', '', 'two thousand twenty six – twenty seven UEFA Champions League'],
  ['9/11 conspiracy theories', '', 'nine / eleven conspiracy theories'],
  ['Charles Spencer, 9th Earl Spencer', '', 'Charles Spencer, ninth Earl Spencer'],
  ['Charles Spencer, 9th Earl Spencer', '9th:drop', 'Charles Spencer,  Earl Spencer'],
  ['18th BRICS summit', '', 'eighteenth BRICS summit'],
  ['78th Primetime Emmy Awards', '', 'seventy eighth Primetime Emmy Awards'],
  ['1st 2nd 3rd 4th 11th 12th 13th 20th 21st 100th 101st 1000th 0th', '', 'first second third fourth eleventh twelfth thirteenth twentieth twenty first one hundredth one hundred first one thousandth zeroth'],
  ['1th 2st 5thavenue', '', 'one th two st five thavenue'],
  ['Ke$ha', '', 'Kesha'],
  ['Ke$ha', '$:drop', 'Keha'],
  ['P!nk', '', 'Pink'],
  ['Hello!', '', 'Hello!'],
  ['$5 off', '', '$ five off'],
  ['Bl1nk', '', 'Blink'],
  ['Bl1nk', '1:spell', 'Bl one nk'],
  ['h3llo l33t', '', 'hello leet'],
  ['Se7en', '', 'Seten'],
  ['R2D2 C3PO MI6 3M mp3', '', 'R two D two CePO MI six three M mp three'],
  ['1337', '', 'one thousand three hundred thirty seven'],
  ['1337', '1337:letter', 'ieet'],
  ['1337', '1337:year', 'thirteen thirty seven'],
  ['182', '182:letter', 'one hundred eighty two'],
  ['AT&T', '', 'AT and T'],
  ['AT&T', '&:drop', 'ATT'],
  ['Me@Home', '', 'MeaHome'],
  ['Me@Home', '@:spell', 'Me at Home'],
  ['@home', '', 'ahome'],
  ['C++', '', 'C plus plus'],
  ['C++', '+:drop', 'C'],
  ['1,000', '', 'one thousand'],
  ['1,000', '1000:digits', 'one zero zero zero'],
  ['1,000,000', '', ''],
  ['1,000,000', '1000000:digits', 'one zero zero zero zero zero zero'],
  ['90210', '', ''],
  ['90210', '90210:digits', 'nine zero two one zero'],
  ['Beverly Hills 90210', '', 'Beverly Hills '],
  ['1,2', '', 'one , two'],
  ['007', '', 'seven'],
  ['007', '007:digits', 'zero zero seven'],
  ['0', '', 'zero'],
  ['0', '0:oh', 'oh'],
  ['8', '8:ate', 'ate'],
  ['1', '1:won', 'won'],
  ['4', '4:for', 'for'],
  ['2000', '', 'two thousand'],
  ['2000', '2000:year', 'two thousand'],
  ['2005', '2005:year', 'twenty oh five'],
  ['1900', '1900:year', 'nineteen hundred'],
  ['1050', '1050:year', 'ten fifty'],
  ['9999', '', 'nine thousand nine hundred ninety nine'],
  ['10 20 30 40 50 60 70 80 90 100 110 999', '', 'ten twenty thirty forty fifty sixty seventy eighty ninety one hundred one hundred ten nine hundred ninety nine'],
  ['Route 66!', '', 'Route sixty six !'],
  ['Ben Shelton 🎾 2026', '', 'Ben Shelton 🎾 two thousand twenty six'],
  ['Beyoncé 2', '', 'Beyoncé two'],
  ['big brother 28', '28:letter', 'big brother twenty eight'],
  ['Test 3 and 3', '3:drop', 'Test  and '],
  ['Test 3 and 3', '5:drop', 'Test three and three'],
  ['Test 3 and 3', '3:oh', 'Test three and three'],
  ['', '', ''],
  ['no items here', '', 'no items here'],
];
