//! The readings table. GENERATED by `scripts/gen-readings.py` from `scripts/readings.json`; do not edit.
//!
//! Read by `readings.rs`, whose tests walk `CASES`; the TypeScript side
//! carries the identical table in `packages/engine/src/readingsTable.ts`.

/// One character of the pool that is not a letter: a digit or a symbol.
pub(crate) struct Character {
    pub ch: char,
    /// An item only with a letter on both sides; elsewhere it is punctuation.
    pub inside_word_only: bool,
    /// The letters it may stand for (the leet readings), in the order offered.
    pub letters: &'static [char],
}

pub(crate) static CHARACTERS: [Character; 18] = [
    Character { ch: '0', inside_word_only: false, letters: &['o'] },
    Character { ch: '1', inside_word_only: false, letters: &['i', 'l'] },
    Character { ch: '2', inside_word_only: false, letters: &['z'] },
    Character { ch: '3', inside_word_only: false, letters: &['e'] },
    Character { ch: '4', inside_word_only: false, letters: &['a'] },
    Character { ch: '5', inside_word_only: false, letters: &['s'] },
    Character { ch: '6', inside_word_only: false, letters: &['g', 'b'] },
    Character { ch: '7', inside_word_only: false, letters: &['t', 'v'] },
    Character { ch: '8', inside_word_only: false, letters: &['b'] },
    Character { ch: '9', inside_word_only: false, letters: &['g'] },
    Character { ch: '@', inside_word_only: false, letters: &['a'] },
    Character { ch: '$', inside_word_only: true, letters: &['s'] },
    Character { ch: '!', inside_word_only: true, letters: &['i'] },
    Character { ch: '?', inside_word_only: true, letters: &[] },
    Character { ch: '&', inside_word_only: false, letters: &[] },
    Character { ch: '%', inside_word_only: false, letters: &[] },
    Character { ch: '+', inside_word_only: false, letters: &['t'] },
    Character { ch: '#', inside_word_only: false, letters: &[] },
];

/// The defaults, as a queue's summary records them.
pub static DEFAULTS: [(&str, &str); 2] = [
    ("digits", "self"),
    ("symbols", "self"),
];

/// `(input, overrides as item:name pairs, the read text)`, walked by the tests.
#[cfg_attr(not(test), allow(dead_code))]
pub(crate) static CASES: [(&str, &str, &str); 57] = [
    ("Blink-182", "", "Blink-182"),
    ("Blink-182", "1:drop,8:drop,2:drop", "Blink-"),
    ("Blink-182", "1:i,8:b,2:z", "Blink-ibz"),
    ("Blink-182", "1:l", "Blink-l82"),
    ("2 Fast 2 Furious", "", "2 Fast 2 Furious"),
    ("2 Fast 2 Furious", "2:drop", " Fast  Furious"),
    ("Area 51", "", "Area 51"),
    ("Reacher season 4", "", "Reacher season 4"),
    ("Reacher season 4", "4:drop", "Reacher season "),
    ("Sardar 2", "2:drop", "Sardar "),
    ("Como 1907", "", "Como 1907"),
    ("2026–27 UEFA Champions League", "", "2026–27 UEFA Champions League"),
    ("9/11 conspiracy theories", "", "9/11 conspiracy theories"),
    ("Charles Spencer, 9th Earl Spencer", "", "Charles Spencer, 9th Earl Spencer"),
    ("18th BRICS summit", "1:drop,8:drop", "th BRICS summit"),
    ("1st 2nd 3rd 4th 11th 12th 13th 21st 100th", "", "1st 2nd 3rd 4th 11th 12th 13th 21st 100th"),
    ("1,000", "", "1,000"),
    ("1,000", "0:drop", "1,"),
    ("1,000,000", "1:drop,0:drop", ",,"),
    ("Ke$ha", "", "Ke$ha"),
    ("Ke$ha", "$:s", "Kesha"),
    ("Ke$ha", "$:drop", "Keha"),
    ("P!nk", "", "P!nk"),
    ("P!nk", "!:i", "Pink"),
    ("wh?t", "", "wh?t"),
    ("Hello!", "", "Hello"),
    ("what?", "", "what"),
    ("Hello! World?", "", "Hello World"),
    ("wow!!", "", "wow"),
    ("a!b!c", "", "a!b!c"),
    ("$5 off", "", "5 off"),
    ("Bl1nk", "", "Bl1nk"),
    ("Bl1nk", "1:i", "Blink"),
    ("h3llo l33t", "3:e", "hello leet"),
    ("Se7en", "7:v", "Seven"),
    ("Se7en", "7:t", "Seten"),
    ("R2D2 C3PO MI6 3M mp3", "", "R2D2 C3PO MI6 3M mp3"),
    ("1337", "1:l,3:e,7:t", "leet"),
    ("AT&T", "", "AT&T"),
    ("AT&T", "&:drop", "ATT"),
    ("Me@Home", "@:a", "MeaHome"),
    ("@home", "", "@home"),
    ("C++", "", "C++"),
    ("C++", "+:t", "Ctt"),
    ("#1 fan", "", "#1 fan"),
    ("50% off", "", "50% off"),
    ("Beverly Hills 90210", "", "Beverly Hills 90210"),
    ("Beverly Hills 90210", "0:drop", "Beverly Hills 921"),
    ("Route 66!", "", "Route 66"),
    ("Ben Shelton 🎾 2026", "", "Ben Shelton 🎾 2026"),
    ("Beyoncé 2", "", "Beyoncé 2"),
    ("Test 3 and 3", "3:e", "Test e and e"),
    ("Test 3 and 3", "5:drop", "Test 3 and 3"),
    ("Test 3 and 3", "3:spell", "Test 3 and 3"),
    ("Test 3 and 3", "3:q", "Test 3 and 3"),
    ("", "", ""),
    ("no items here", "", "no items here"),
];
