/**
 * The term classes' files (decision D63): the terms the dictionary carries
 * beside its words, each with its class, read from `data/vocabulary/` and
 * built into the `classes` artifact by `dict:build`.
 *
 * A class file is one JSON object per line with a `term`, as `additions.jsonl`
 * has a `word`, each through its own schema (`vocab.ts`): `symbols`,
 * `shorthand`, `blends` and `acronyms` since phase N4, `slang` once G1 pins
 * its Wiktionary extract. The names list is the `names` class, every name of
 * `NAME_FLOOR` letters or more. A class with no file has no terms; with no
 * term anywhere the build emits no artifact and the site searches words
 * alone. Numerals and leet are generated by the engine and have no file.
 */
import { CLASSES, type ClassName } from '../../../packages/engine/src/protocol.ts';
import type { ClassTerm } from './format.ts';
import { NAME_FLOOR } from './tokens.ts';
import { NAMES_PATH, VOCAB_DIR, readClassFiles, readNames } from './vocab.ts';

export { CLASS_FILES } from './vocab.ts';

/** A class's bit: its place in the plan's table, as the engine has it. */
export function classBit(name: ClassName): number {
  return 1 << CLASSES.indexOf(name);
}

/** One term as a class file lists it, with the class it was listed under; the other fields are the file's own. */
export type ClassEntry = { term: string; class: ClassName };

/**
 * Every term of every class file that exists, with its class, and every name
 * of the names list under the floor as `names`. A line the schema refuses is
 * an error naming it, since the engine would refuse the artifact or, worse,
 * carry a term nobody vouched for. A term listed in two files gives two
 * entries, which `classTerms` merges into one term with both bits; a line's
 * `also` only declares that this is meant (`vocab:check` holds it to the
 * files), so the files and the list alone decide the bits.
 */
export async function readClassEntries(dir = VOCAB_DIR, namesPath = NAMES_PATH): Promise<ClassEntry[]> {
  const out: ClassEntry[] = [];
  for (const [name, lines] of await readClassFiles(dir)) {
    for (const line of lines) out.push({ term: line.term, class: name });
  }
  for (const { name } of await readNames(namesPath)) {
    if (name.length < NAME_FLOOR) continue;
    out.push({ term: name, class: 'names' });
  }
  return out;
}

/** The entries as the artifact carries them: one per term, its classes' bits merged. */
export function classTerms(entries: readonly ClassEntry[]): ClassTerm[] {
  const bits = new Map<string, number>();
  for (const { term, class: name } of entries) bits.set(term, (bits.get(term) ?? 0) | classBit(name));
  return [...bits.entries()].map(([term, b]) => ({ term, bits: b })).sort((a, b) => (a.term < b.term ? -1 : a.term > b.term ? 1 : 0));
}

/** How many terms each class has, for the manifest; only the classes with any. */
export function classCounts(entries: readonly ClassEntry[]): Partial<Record<ClassName, number>> {
  const counts: Partial<Record<ClassName, number>> = {};
  for (const { class: name } of entries) counts[name] = (counts[name] ?? 0) + 1;
  return counts;
}
