/**
 * The term classes' files (decision D63): the terms the dictionary carries
 * beside its words, each with its class, read from `data/vocabulary/` and
 * built into the `classes` artifact by `dict:build`.
 *
 * A class file is one JSON object per line with a `term`, as `additions.jsonl`
 * has a `word`; phase N4 seeds the files and gives each its schema, gloss and
 * trace and `vocab:check` over them, and the names list joins then with its
 * floor of three letters. Until a file exists the class has no terms, the
 * build emits no artifact, and the site searches words alone: nothing here
 * changes a dictionary of words alone by a byte. Numerals and leet are
 * generated by the engine and have no file.
 */
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

import { CLASSES, type ClassName } from '../../../packages/engine/src/protocol.ts';
import { TERM_PATTERN, type ClassTerm } from './format.ts';
import { VOCAB_DIR } from './vocab.ts';

/** The classes a file lists terms for, and the file. */
export const CLASS_FILES: Readonly<Partial<Record<ClassName, string>>> = {
  symbols: 'symbols.jsonl',
  shorthand: 'shorthand.jsonl',
  blends: 'blends.jsonl',
  acronyms: 'acronyms.jsonl',
  slang: 'slang.jsonl',
};

/** A class's bit: its place in the plan's table, as the engine has it. */
export function classBit(name: ClassName): number {
  return 1 << CLASSES.indexOf(name);
}

/** One term as a class file lists it; the other fields are the file's own. */
export type ClassEntry = { term: string; class: ClassName };

/**
 * Every term of every class file that exists, with its class. A file that is
 * absent lists nothing; a line without a `term` of the pool's characters is
 * an error, since the engine would refuse the artifact.
 */
export async function readClassEntries(dir = VOCAB_DIR): Promise<ClassEntry[]> {
  const out: ClassEntry[] = [];
  for (const [name, file] of Object.entries(CLASS_FILES) as [ClassName, string][]) {
    let text: string;
    try {
      text = await readFile(resolve(dir, file), 'utf8');
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') continue;
      throw error;
    }
    for (const line of text.split('\n')) {
      if (line.trim().length === 0) continue;
      const parsed = JSON.parse(line) as { term?: unknown };
      const term = parsed.term;
      if (typeof term !== 'string' || !TERM_PATTERN.test(term)) {
        throw new Error(`${file}: ${JSON.stringify(term)} is not a term of letters, digits and the pool's symbols`);
      }
      out.push({ term, class: name });
    }
  }
  return out;
}

/** The entries as the artifact carries them: one per term, its classes' bits merged. */
export function classTerms(entries: readonly ClassEntry[]): ClassTerm[] {
  const bits = new Map<string, number>();
  for (const { term, class: name } of entries) bits.set(term, (bits.get(term) ?? 0) | classBit(name));
  return [...bits.entries()].map(([term, b]) => ({ term, bits: b })).sort((a, b) => (a.term < b.term ? -1 : a.term > b.term ? 1 : 0));
}

/** How many terms each class has, for the manifest; only the classes with any. */
export function classCounts(entries: readonly ClassEntry[]): Partial<Record<ClassName, number>> {
  const counts: Partial<Record<ClassName, number>> = {};
  for (const { class: name } of entries) counts[name] = (counts[name] ?? 0) + 1;
  return counts;
}
