#!/usr/bin/env python3
"""
Generate the accent-folding table shared by the Rust engine and the TypeScript
engine package.

    python3 scripts/gen-fold-table.py

Every accented Latin letter is forced to its unaccented base letter. The table
is derived from Unicode NFKD (decompose, drop combining marks, keep ASCII
letters) over the Latin blocks, plus a hand-written list for Latin letters that
have no decomposition (ß, æ, œ, ø, đ, ł, þ, ð, ı). It is generated once and
committed, rather than computed at run time, because a full Unicode
normalization library adds ~50 KB to the compressed WASM payload for a job that
needs a few hundred entries.

Both emitted files are checked by tests against a real normalizer over the
same ranges (`unicode-normalization` in Rust, `String.prototype.normalize` in
TypeScript), so the table cannot drift from NFKD without a test noticing.
"""
from __future__ import annotations

import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RUST_OUT = ROOT / "crates/anagram-core/src/fold_table.rs"
TS_OUT = ROOT / "packages/engine/src/foldTable.ts"

# Inclusive code point ranges the table covers. Anything outside folds to
# nothing (it is not a Latin letter) in both implementations.
RANGES = [
    (0x00C0, 0x024F),  # Latin-1 Supplement, Latin Extended-A, Latin Extended-B
    (0x1E00, 0x1EFF),  # Latin Extended Additional (Vietnamese, Welsh, ...)
    (0xFB00, 0xFB06),  # Latin ligatures ﬀ ﬁ ﬂ ﬃ ﬄ ﬅ ﬆ
    (0xFF21, 0xFF5A),  # Fullwidth A-Z, a-z
]

# Latin letters NFKD leaves alone. Lowercase output, like everything else.
SPECIAL = {
    "ß": "ss", "ẞ": "ss",
    "æ": "ae", "Æ": "ae",
    "œ": "oe", "Œ": "oe",
    "ø": "o", "Ø": "o",
    "đ": "d", "Đ": "d",
    "ł": "l", "Ł": "l",
    "þ": "th", "Þ": "th",
    "ð": "d", "Ð": "d",
    "ı": "i",
}


def nfkd_fold(char: str) -> str:
    out = []
    for piece in unicodedata.normalize("NFKD", char):
        if unicodedata.category(piece).startswith("M"):
            continue
        lower = piece.lower()
        if "a" <= lower <= "z":
            out.append(lower)
    return "".join(out)


def build() -> dict[str, str]:
    table: dict[str, str] = {}
    for lo, hi in RANGES:
        for cp in range(lo, hi + 1):
            char = chr(cp)
            folded = nfkd_fold(char)
            if folded:
                table[char] = folded
    # SPECIAL wins where NFKD produced nothing (or something else).
    table.update(SPECIAL)
    return dict(sorted(table.items(), key=lambda kv: ord(kv[0])))


def emit_rust(table: dict[str, str]) -> str:
    lines = [
        "//! Accent folding table. GENERATED by `scripts/gen-fold-table.py`; do not edit.",
        "//!",
        "//! Sorted by code point, so `normalize()` can binary-search it. Verified",
        "//! against `unicode-normalization` in the tests below this file.",
        "",
        "/// `(character, its lowercase ASCII letters)`, sorted by character.",
        f"pub(crate) static FOLD: [(char, &str); {len(table)}] = [",
    ]
    for char, folded in table.items():
        lines.append(f"    ('\\u{{{ord(char):04x}}}', \"{folded}\"), // {char}")
    lines.append("];")
    lines.append("")
    lines.append("/// Inclusive code point ranges the table was generated over. Used by the")
    lines.append("/// tests to check the table against a real normalizer.")
    lines.append("#[cfg_attr(not(test), allow(dead_code))]")
    lines.append("pub(crate) const RANGES: [(u32, u32); %d] = [" % len(RANGES))
    for lo, hi in RANGES:
        lines.append(f"    (0x{lo:04X}, 0x{hi:04X}),")
    lines.append("];")
    return "\n".join(lines) + "\n"


def emit_ts(table: dict[str, str]) -> str:
    lines = [
        "// Accent folding table. GENERATED by `scripts/gen-fold-table.py`; do not edit.",
        "//",
        "// Verified against `String.prototype.normalize('NFKD')` in fold.test.ts.",
        "",
        "/** Character -> its lowercase ASCII letters. */",
        "export const FOLD_TABLE: Readonly<Record<string, string>> = {",
    ]
    for char, folded in table.items():
        lines.append(f"  '\\u{{{ord(char):04x}}}': '{folded}', // {char}")
    lines.append("};")
    lines.append("")
    lines.append("/** Inclusive code point ranges the table was generated over. */")
    lines.append("export const FOLD_RANGES: readonly (readonly [number, number])[] = [")
    for lo, hi in RANGES:
        lines.append(f"  [0x{lo:04X}, 0x{hi:04X}],")
    lines.append("];")
    return "\n".join(lines) + "\n"


def main() -> None:
    table = build()
    RUST_OUT.write_text(emit_rust(table), encoding="utf-8")
    TS_OUT.write_text(emit_ts(table), encoding="utf-8")
    print(f"{len(table)} entries -> {RUST_OUT.relative_to(ROOT)}, {TS_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
