#!/usr/bin/env python3
"""
Emit the readings table shared by the Rust engine and the TypeScript engine
package from its one source, `scripts/readings.json`.

    python3 scripts/gen-readings.py

An item of an input is a run of digits, an ordinal, or one of the symbols in
the table (roadmap phase N, the literal rule, decisions D62 and D63). Nothing
is converted: until the literal phase counts digits and symbols as characters
of the pool, every item is left out (`drop`), and the item finder, written by
hand on each side (`crates/anagram-core/src/readings.rs`,
`packages/engine/src/readings.ts`), is held to the emitted cases by a test on
each side, so the two cannot drift from each other or from the table.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "scripts/readings.json"
RUST_OUT = ROOT / "crates/anagram-core/src/readings_table.rs"
TS_OUT = ROOT / "packages/engine/src/readingsTable.ts"

HEADER = "GENERATED by `scripts/gen-readings.py` from `scripts/readings.json`; do not edit."


def rs_str(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def ts_str(value: str) -> str:
    """A single-quoted TypeScript string, as the rest of the package writes them."""
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def emit_rust(table: dict) -> str:
    symbols = table["symbols"]
    lines = [
        f"//! The readings table. {HEADER}",
        "//!",
        "//! Read by `readings.rs`, whose tests walk `CASES`; the TypeScript side",
        "//! carries the identical table in `packages/engine/src/readingsTable.ts`.",
        "",
        "/// One symbol the item finder knows.",
        "pub(crate) struct Symbol {",
        "    pub ch: char,",
        "    /// An item only with a letter on both sides; elsewhere it is punctuation.",
        "    pub inside_word_only: bool,",
        "}",
        "",
        f"pub(crate) static SYMBOLS: [Symbol; {len(symbols)}] = [",
    ]
    for ch, spec in symbols.items():
        lines.append(f"    Symbol {{ ch: {ch!r}, inside_word_only: {'true' if spec['insideWordOnly'] else 'false'} }},")
    lines.append("];")
    lines.append("")
    lines.append("/// The defaults, as a queue's summary records them.")
    defaults = table["defaults"]
    lines.append(f"pub static DEFAULTS: [(&str, &str); {len(defaults)}] = [")
    for key, value in defaults.items():
        lines.append(f"    ({rs_str(key)}, {rs_str(value)}),")
    lines.append("];")
    lines.append("")
    lines.append("/// `(input, overrides as item:name pairs, the read text)`, walked by the tests.")
    lines.append("#[cfg_attr(not(test), allow(dead_code))]")
    lines.append(f"pub(crate) static CASES: [(&str, &str, &str); {len(table['cases'])}] = [")
    for text, overrides, expected in table["cases"]:
        lines.append(f"    ({rs_str(text)}, {rs_str(overrides)}, {rs_str(expected)}),")
    lines.append("];")
    return "\n".join(lines) + "\n"


def emit_ts(table: dict) -> str:
    symbols = table["symbols"]
    lines = [
        f"// The readings table. {HEADER}",
        "//",
        "// Read by `readings.ts`, whose tests walk `READING_CASES` and check this",
        "// file against the JSON; the Rust side carries the identical table in",
        "// `crates/anagram-core/src/readings_table.rs`.",
        "",
        "/** One symbol the item finder knows. */",
        "export type SymbolSpec = {",
        "  /** An item only with a letter on both sides; elsewhere it is punctuation. */",
        "  readonly insideWordOnly: boolean;",
        "};",
        "",
        "export const SYMBOLS: Readonly<Record<string, SymbolSpec>> = {",
    ]
    for ch, spec in symbols.items():
        lines.append(f"  {ts_str(ch)}: {{ insideWordOnly: {'true' if spec['insideWordOnly'] else 'false'} }},")
    lines.append("};")
    lines.append("")
    lines.append("/** The defaults, as a queue's summary records them. */")
    lines.append("export const READING_DEFAULTS: Readonly<Record<string, string>> = {")
    for key, value in table["defaults"].items():
        lines.append(f"  {ts_str(key)}: {ts_str(value)},")
    lines.append("};")
    lines.append("")
    lines.append("/** `[input, overrides as item:name pairs, the read text]`, walked by the tests. */")
    lines.append("export const READING_CASES: readonly (readonly [string, string, string])[] = [")
    for text, overrides, expected in table["cases"]:
        lines.append(f"  [{ts_str(text)}, {ts_str(overrides)}, {ts_str(expected)}],")
    lines.append("];")
    return "\n".join(lines) + "\n"


def main() -> None:
    table = json.loads(SOURCE.read_text(encoding="utf-8"))
    RUST_OUT.write_text(emit_rust(table), encoding="utf-8")
    TS_OUT.write_text(emit_ts(table), encoding="utf-8")
    print(f"{len(table['cases'])} cases -> {RUST_OUT.relative_to(ROOT)}, {TS_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
