#!/usr/bin/env python3
"""
Emit the readings table shared by the Rust engine and the TypeScript engine
package from its one source, `scripts/readings.json`.

    python3 scripts/gen-readings.py

An item of an input is one distinct digit or symbol of the pool (roadmap
phase N, the literal rule, decisions D62 and D63). It reads as itself, as one
of its leet letters, or as `drop`; nothing is converted. The item finder,
written by hand on each side (`crates/anagram-core/src/readings.rs`,
`packages/engine/src/readings.ts`), is held to the emitted cases by a test on
each side, so the two cannot drift from each other or from the table.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "scripts/readings.json"
RUST_OUT = ROOT / "crates/anagram-core/src/readings_table.rs"
TS_OUT = ROOT / "packages/engine/src/readingsTable.ts"

HEADER = "GENERATED by `scripts/gen-readings.py` from `scripts/readings.json`; do not edit."


def rs_str(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def ts_str(value: str) -> str:
    """A single-quoted TypeScript string, as the rest of the package writes them."""
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def emit_rust(table: dict) -> str:
    characters = table["characters"]
    lines = [
        f"//! The readings table. {HEADER}",
        "//!",
        "//! Read by `readings.rs`, whose tests walk `CASES`; the TypeScript side",
        "//! carries the identical table in `packages/engine/src/readingsTable.ts`.",
        "",
        "/// One character of the pool that is not a letter: a digit or a symbol.",
        "pub(crate) struct Character {",
        "    pub ch: char,",
        "    /// An item only with a letter on both sides; elsewhere it is punctuation.",
        "    pub inside_word_only: bool,",
        "    /// The letters it may stand for (the leet readings), in the order offered.",
        "    pub letters: &'static [char],",
        "}",
        "",
        f"pub(crate) static CHARACTERS: [Character; {len(characters)}] = [",
    ]
    for ch, spec in characters.items():
        letters = ", ".join(repr(l) for l in spec["letters"])
        inside = "true" if spec["insideWordOnly"] else "false"
        lines.append(f"    Character {{ ch: {ch!r}, inside_word_only: {inside}, letters: &[{letters}] }},")
    lines.append("];")
    lines.append("")
    lines.append("/// The defaults, as a queue's summary records them.")
    defaults = table["defaults"]
    lines.append(f"pub static DEFAULTS: [(&str, &str); {len(defaults)}] = [")
    for key, value in defaults.items():
        lines.append(f"    ({rs_str(key)}, {rs_str(value)}),")
    lines.append("];")
    lines.append("")
    lines.append("/// `(input, overrides as item:name pairs, the read text)`, walked by the tests.")
    lines.append("#[cfg_attr(not(test), allow(dead_code))]")
    lines.append(f"pub(crate) static CASES: [(&str, &str, &str); {len(table['cases'])}] = [")
    for text, overrides, expected in table["cases"]:
        lines.append(f"    ({rs_str(text)}, {rs_str(overrides)}, {rs_str(expected)}),")
    lines.append("];")
    return "\n".join(lines) + "\n"


def emit_ts(table: dict) -> str:
    characters = table["characters"]
    lines = [
        f"// The readings table. {HEADER}",
        "//",
        "// Read by `readings.ts`, whose tests walk `READING_CASES` and check this",
        "// file against the JSON; the Rust side carries the identical table in",
        "// `crates/anagram-core/src/readings_table.rs`.",
        "",
        "/** One character of the pool that is not a letter: a digit or a symbol. */",
        "export type CharacterSpec = {",
        "  /** An item only with a letter on both sides; elsewhere it is punctuation. */",
        "  readonly insideWordOnly: boolean;",
        "  /** The letters it may stand for (the leet readings), in the order offered. */",
        "  readonly letters: readonly string[];",
        "};",
        "",
        "export const CHARACTERS: Readonly<Record<string, CharacterSpec>> = {",
    ]
    for ch, spec in characters.items():
        letters = ", ".join(ts_str(l) for l in spec["letters"])
        inside = "true" if spec["insideWordOnly"] else "false"
        lines.append(f"  {ts_str(ch)}: {{ insideWordOnly: {inside}, letters: [{letters}] }},")
    lines.append("};")
    lines.append("")
    lines.append("/** The defaults, as a queue's summary records them. */")
    lines.append("export const READING_DEFAULTS: Readonly<Record<string, string>> = {")
    for key, value in table["defaults"].items():
        lines.append(f"  {ts_str(key)}: {ts_str(value)},")
    lines.append("};")
    lines.append("")
    lines.append("/** `[input, overrides as item:name pairs, the read text]`, walked by the tests. */")
    lines.append("export const READING_CASES: readonly (readonly [string, string, string])[] = [")
    for text, overrides, expected in table["cases"]:
        lines.append(f"  [{ts_str(text)}, {ts_str(overrides)}, {ts_str(expected)}],")
    lines.append("];")
    return "\n".join(lines) + "\n"


def main() -> None:
    table = json.loads(SOURCE.read_text(encoding="utf-8"))
    for ch, spec in table["characters"].items():
        if len(ch) != 1 or (not ch.isdigit() and ch.isalnum()):
            raise SystemExit(f"{ch!r} is not one digit or symbol")
        if any(len(l) != 1 or not ("a" <= l <= "z") for l in spec["letters"]):
            raise SystemExit(f"{ch!r}: every letter reading is one lowercase letter")
    RUST_OUT.write_text(emit_rust(table), encoding="utf-8")
    TS_OUT.write_text(emit_ts(table), encoding="utf-8")
    print(f"{len(table['cases'])} cases -> {RUST_OUT.relative_to(ROOT)}, {TS_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
